# file: .github/workflows/main.yml
name: main
on: push
jobs:
  setup:
    name: run setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        npm-version: [6.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          npm-version: ${{ matrix.npm-version }}
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: make test
      - name: Lint
  
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}run: make lint
